### ISSUE TITLE
Turning off location completely

### ISSUE THREAD

**Issue by ghost** [ltGuillaume/Redshift-Tray#12]
I appreciate that this is a marginal user case, but I really just want to turn Redshift on and off as I please, with no automated times. Also, even though apps *can* locate me from my IP, I'd rather they don't.

Any handy configuration setting to kill the autolocation function?

**Comment by ltguillaume** [comment]
I guess you could just fill in a fake location via More settings (fill in whatever after longitude and latitude), enable "Start disabled" and only use the forced mode (see hotkeys).

**Comment by ghost** [comment]
That defeats the purpose of having Redshift Tray installed (ie., having it in the tray for convenience).
I guess that's a "no" to my question, then?

**Comment by ltguillaume** [comment]
It's got either location-based automation, or you can specify custom times. Otherwise, it's up to manual changes via forced mode.

I don't really see why it defeats the purpose, as you're perfectly able to use hotkeys, or the system tray icon, to do these changes. I'm not sure if I get what you'd like to see changed, it's all there. You mean you want to double-click the icon to set it to "Forced" instead of "Enabled"?

**Comment by ghost** [comment]
>I don't really see why it defeats the purpose

You're probably right, I've come at this wrong expecting it to work simply as a light switch. I'll give your suggestion a go,

Thanks!

**Comment by ltguillaume** [comment]
@haverholm Please have a look at https://github.com/ltGuillaume/Redshift-Tray/releases/tag/1.9.0 as it makes the shortcut RAlt+End return from forced mode to the previous mode, instead of always to enabled. It's a bit easier to use in your case, together with RAlt+Home, instead of Alt+End to set the disabled state, and it makes more sense.
