### ISSUE TITLE
Screen temperature resets when Windows turns off displays due to Power Saving options

### ISSUE THREAD

**Issue by keb** [ltGuillaume/Redshift-Tray#13]
Experienced this last night on my Windows 10 64-bit LTSC machine. I have my Power Options set to turn off my two displays after 10 minutes of inactivity. Upon waking, the screen temperature seems to reset back to its default temperature as if redshift malfunctioned. I have to disable and re-enable redshift to fix the temperature.

I actually experienced this using the redshift CLI before discovering this tool. Wondering if perhaps there is an option I am overlooking. Either way, kudos to you and this brilliant utility.

**Comment by ltguillaume** [comment]
Hmmz, I haven't experienced this before. Can you check if `redshift.exe` is still running at that moment (it does look like it, judging from your description).

In any case, the root of the problem is indeed with Redshift itself. I just checked all the commits since the build that is "shipped" with Redshift Tray, and it doesn't seem there was any fix for your issue. 
1. Have you found anything among https://github.com/jonls/redshift/issues that relates to your problem?
2. Is Redshift still running when your monitor is turning back on? Or did it crash?
3. Have you disabled the Windows 10 night mode?
3. (Especially when it concerns a laptop) Could there be some manufacturer tool that applies a color profile? I know ASUS has this, for example.

**Comment by keb** [comment]
Thanks for the speedy reply.

1. Looked to the best of my ability, but haven't found anyone else report this issue. Might be in part because redshift is more popular on Linux than Windows.
2. Yes, Redshift is still running.
3. Yes W10 Nightmode is disabled
4. I'm running this on my desktop with a clean LTSC copy of W10. So there doesn't seem to be any other utility that applies a color profile, or any unknown processes running as far as I can tell.

Either way, as you suggested, this problem seems to lie with Redshift itself, and not so much your utility. I will try to replicate on another PC sometime this weekend. Thanks for your help.

**Comment by ltguillaume** [comment]
Yes, perhaps you can find help with the Redshift author. I can't reproduce it myself, so it isn't within my power to fiddle with parameters to see if that helps, either. Let me know what you find! :)

**Comment by ltguillaume** [comment]
@keb FWIW, v2.0.0 has a feature to periodically check whether _redshift.exe_ is still running. Just set `keepaliveseconds=5` and see if it fixes the issue for you.

You said Redshift was still running, but perhaps you meant that Redshift Tray was still running? In that case, this may work nicely.

**Comment by ltguillaume** [comment]
@keb You're still using this?

**Comment by keb** [comment]
Hey @ltGuillaume , thanks for the ping. I have not been using Redshift Tray, (resorted back to Windows 10's built-in night light), but I will try again when I get home. Great job on the new feature! Hope you had a great holiday.

**Comment by keb** [comment]
@ltGuillaume Sorry for the wait. Finally got around to testing this (you know how it is).

Unfortunately, it seems this setting does not aid in the issue. It does not seem to appear that `redshift.exe` crashes persay, it just... stops working until reset.

**Comment by ltguillaume** [comment]
So sorry it didn't help. I needed this new setting for when switching between HDMI and internal display sometimes, but also when coming out of hibernation/standby, so I was hoping it would also work for you. Then I guess the problem is indeed purely related to Redshift, or perhaps Windows resets the gamma and Redshift only picks it up after a while (when the sun is lower)?
