### ISSUE TITLE
[request] Provide a custom build

### ISSUE THREAD

**Issue by omeringen** [ltGuillaume/Redshift-Tray#16]
Hi,
The computer i use at work has an antivirus with a "password protection", so there is no way to disable. 
Is it possible to provide a build without AutoHotkey script ?

Thanks.

**Comment by ltguillaume** [comment]
Sorry, but this whole thing _is_ an AutoHotkey script. The `rstray.exe` file is nothing more than the script wrapped in the AutoHotkey interpreter.

You could try out a previous version, since they may have been reported as a false positive enough times for your antivirus to have picked up.

**Comment by ltguillaume** [comment]
@omeringen I've created a package that uses the default AutoHotkey runtime, instead of compiling it with Ahk2Exe. Perhaps this will work for you, please do try as it could prove to be an alternative way of distributing RsTray.

You can run the script by double-clicking `!run.cmd`.
[redshift-tray_2.0.0ahk.zip](https://github.com/ltGuillaume/Redshift-Tray/files/5824283/redshift-tray_2.0.0ahk.zip)

**Comment by omeringen** [comment]
@ltGuillaume ,
Works fine for me ! Thanks.

**Comment by ltguillaume** [comment]
Ok, cool, thanks for the feedback. I'll consider changing the script so that it can be run like this, too. The only downside is a flickering tray icon in some cases.

**Comment by ltguillaume** [comment]
@omeringen The script should not need any alterations anymore to run it uncompiled.
