### ISSUE TITLE
Flashing when changing brightness

### ISSUE THREAD

**Issue by no008080** [ltGuillaume/Redshift-Tray#21]
When adjusting brightness, the screen flashes in its default brightness and color temperature, especially noticeable in the late hours?
Is there any fix planned for that, because it hurts the retinas quite a a bit?

I'm using the Windows 10 version 2.2.0.

**Comment by ltguillaume** [comment]
I don't have this issue. Could you post the contents of the file `rstray.ini` here? You should remove the lines `latitude=???` and `longitude=???` if you don't want to give away your location.

**Comment by no008080** [comment]
Sorry for the late reply.
As it turns out, this only happens if `keepcalibration=1`, so my best guess is that it doesn't play nice with WIndows' in-house calibration settings. Turning it off fixed the flashing.

I don't know if others experienced the same or if this warrants an issue, so i leave it up to you if you want to close this issue,

**Comment by ltguillaume** [comment]
Not sure why I didn't respond yet, sorry about that. But in order to keep the calibration of your monitor, I see no other way than to reset the calibration before each brightness adjustment. I believe the effect otherwise was quite horrible, at least for some setups.

These are just consequences of Redshift, and since this is just a wrapper/UI for it, I can't do anything else than make this behavior "optional".
